language: php
cache:
    directories:
        - $HOME/.composer/cache
        - vendor
php:
    - 7.0
    - 7.1

before_install: 
    - phpenv config-rm xdebug.ini || return 0,
    - travis_retry composer self-update

install: 
    - travis_retry composer install --dev --no-interaction 
    - composer show 

script: 
    - composer cs-check
    - composer test 
