language: php
services:
    - postgresql

cache:
    directories:
        - $HOME/.composer/cache
        - vendor
php:
    - 7.0
    - 7.1

before_install: 
    - phpenv config-rm xdebug.ini || return 0,
    - travis_retry composer self-update

install: 
    - travis_retry composer install --dev --no-interaction 
    - composer show 

before-script:
    - psql -c 'create database space_idle_test;' -U postgres
    - cp .travis.env .env

script: 
    - composer cs-check
    - composer test 
